func get_locations():
    return {
        "sub_area_name": "Phoenix Rising",
        "rooms": [
            "bdcc2_syndiship",
            "syndi_captain",
            "syndi_quarters",
            "syndi_galley",
            "syndi_cargo",
            "syndi_cargo_stairs",
            "syndi_cargo_stairs_down",
            "syndi_upper_stairs",
            "syndi_shower",
            "syndi_storage",
            "syndi_lower_stairs",
            "syndi_lower_hall",
            "syndi_lower_placeholder",
            "syndi_lower_engine",
            "syndi_lower_doorway",
            "syndi_lower_teleporter",
        ],
        "aliases": {
            "bdcc2_syndiship": "Cockpit",
            "syndi_captain": "Captain's Quarters",
            "syndi_quarters": "Crew Bunks",
            "syndi_galley": "Galley",
            "syndi_cargo": "Cargo Hold",
            "syndi_cargo_stairs": "Cargo Stairs (Up)",
            "syndi_cargo_stairs_down": "Cargo Stairs (Down)",
            "syndi_upper_stairs": "Upper Deck Stairs",
            "syndi_shower": "Shower",
            "syndi_storage": "Storage Locker",
            "syndi_lower_stairs": "Stairwell (C1)",
            "syndi_lower_hall": "Main Corridor (C2)",
            "syndi_lower_placeholder": "Empty Room (C3)",
            "syndi_lower_engine": "Engine Room (D2)",
            "syndi_lower_doorway": "Doorway (B2)",
            "syndi_lower_teleporter": "Teleporter Room (A2)",
        },
    }
